---
title: "長庚大學 大數據分析方法 作業三"
output: github_document
---


    

## 網站資料爬取
```{r}
library(rvest) 
PTT<-"https://www.ptt.cc/bbs/NBA/index4628.html"
PTTContent<-read_html(PTT)
post_title <- PTTContent %>% html_nodes(".title") %>% html_text() 
post_title
post_pushnum <- PTTContent %>% html_nodes(".nrec") %>% html_text() 
post_pushnum
post_author <- PTTContent %>% html_nodes(".author") %>% html_text() 
post_author

PTT1<-"https://www.ptt.cc/bbs/NBA/index4627.html"
PTTContent1<-read_html(PTT1)
post_title1 <- PTTContent1 %>% html_nodes(".title") %>% html_text() 
post_title1
post_pushnum1 <- PTTContent1 %>% html_nodes(".nrec") %>% html_text() 
post_pushnum1
post_author1 <- PTTContent1 %>% html_nodes(".author") %>% html_text() 
post_author1

PTT2<-"https://www.ptt.cc/bbs/NBA/index4626.html"
PTTContent2<-read_html(PTT2)
post_title2 <- PTTContent2 %>% html_nodes(".title") %>% html_text() 
post_title2
post_pushnum2 <- PTTContent2 %>% html_nodes(".nrec") %>% html_text() 
post_pushnum2
post_author2 <- PTTContent2 %>% html_nodes(".author") %>% html_text() 
post_author2

PTT3<-"https://www.ptt.cc/bbs/NBA/index4625.html"
PTTContent3<-read_html(PTT3)
post_title3 <- PTTContent3 %>% html_nodes(".title") %>% html_text() 
post_title3
post_pushnum3 <- PTTContent3 %>% html_nodes(".nrec") %>% html_text() 
post_pushnum3
post_author3 <- PTTContent3 %>% html_nodes(".author") %>% html_text() 
post_author3

PTT4<-"https://www.ptt.cc/bbs/NBA/index4624.html"
PTTContent4<-read_html(PTT4)
post_title4 <- PTTContent4 %>% html_nodes(".title") %>% html_text() 
post_title4
post_pushnum4 <- PTTContent4 %>% html_nodes(".nrec") %>% html_text() 
post_pushnum4
post_author4 <- PTTContent4 %>% html_nodes(".author") %>% html_text() 
post_author4

PTT5<-"https://www.ptt.cc/bbs/NBA/index4623.html"
PTTContent5<-read_html(PTT5)
post_title5 <- PTTContent5 %>% html_nodes(".title") %>% html_text() 
post_title5
post_pushnum5 <- PTTContent5 %>% html_nodes(".nrec") %>% html_text() 
post_pushnum5
post_author5 <- PTTContent5 %>% html_nodes(".author") %>% html_text() 
post_author5



NBAdataframe <- data.frame(Title=c(post_title), PushNum=c(post_pushnum), Author=c(post_author))
NBAdataframe

NBAdataframe1 <- data.frame(Title=c(post_title1), PushNum=c(post_pushnum1), Author=c(post_author1))
NBAdataframe1

NBAdataframe2 <- data.frame(Title=c(post_title2), PushNum=c(post_pushnum2), Author=c(post_author2))
NBAdataframe2

NBAdataframe3 <- data.frame(Title=c(post_title3), PushNum=c(post_pushnum3), Author=c(post_author3))
NBAdataframe3

NBAdataframe4 <- data.frame(Title=c(post_title4), PushNum=c(post_pushnum4), Author=c(post_author4))
NBAdataframe4

NBAdataframe5 <- data.frame(Title=c(post_title5), PushNum=c(post_pushnum5), Author=c(post_author5))
NBAdataframe5



dataframeAll<-rbind(NBAdataframe,NBAdataframe1,NBAdataframe2,NBAdataframe3,NBAdataframe4,NBAdataframe5)
dataframeAll
##read_html
##html_nodes
##html_text
```

## 爬蟲結果呈現
```{r}
knitr::kable(
    dataframeAll[1:100,c("Title","PushNum","Author")])
```

## 解釋爬蟲結果 
```{r}
dim(dataframeAll)
```
共爬120個標題，有Title , PushNum , Author 這三個欄位


```{r}
table(dataframeAll$Author)
```

作者Rambo  文章數是23篇

因為我不會運用for迴圈，後來研究了很久發現可以連續複製好幾次就可以爬到很多筆了!
